-- BEGIN TABLE SCIPIO_INFO
CREATE TABLE SCIPIO_INFO
(
   ID            INTEGER     GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   PEI           INTEGER,
   TEI           INTEGER,
   PIN           INTEGER,
   TRANSACTION_ID INTEGER,
   TICKET_ID     INTEGER
);
ALTER TABLE SCIPIO_INFO
   ADD CONSTRAINT SQL_PK_SCIPIO_INFO PRIMARY KEY (ID);

CREATE INDEX APP.SCIPIO_INFO_INDEX_PIN
   ON SCIPIO_INFO (PIN ASC);

CREATE INDEX APP.SCIPIO_INFO_INDEX_TEI
   ON SCIPIO_INFO (TEI ASC);

CREATE INDEX APP.SCIPIO_INFO_INDEX_PEI
   ON SCIPIO_INFO (PIN ASC);

CREATE UNIQUE INDEX APP.SQL120304003054670
   ON SCIPIO_INFO (ID ASC);

CREATE INDEX APP.SQL120304003219950
   ON SCIPIO_INFO (TICKET_ID ASC);

CREATE INDEX APP.SCIPIO_INFO_INDEX_TRANSACTION_ID
   ON SCIPIO_INFO (TRANSACTION_ID ASC);

-- END TABLE SCIPIO_INFO

-- BEGIN FOREIGN KEYS --
ALTER TABLE SCIPIO_INFO
  ADD CONSTRAINT FK_SCIPIO_INFO_TICKET_ID FOREIGN KEY (TICKET_ID)
  REFERENCES TICKET (ID)
   ON UPDATE NO ACTION
   ON DELETE NO ACTION;

ALTER TABLE SCIPIO_INFO
  ADD CONSTRAINT FK_SCIPIO_INFO_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID)
  REFERENCES TRANSACTIONS (ID)
   ON UPDATE NO ACTION
   ON DELETE NO ACTION;

-- END FOREIGN KEYS --


COMMIT;
