/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.floreantpos.ui.dialog;

import java.text.ParseException;
import javax.swing.text.MaskFormatter;

import com.floreantpos.PosException;
import com.floreantpos.main.Application;
import com.floreantpos.model.Ticket;

/**
 *
 * @author Aaron Evans <aarone@one-shore.com>
 */
public class ScipioDialog extends POSDialog {

	private Ticket ticket;
	private int TEI_MAX_LENGTH = 5;
	private int PIN_MAX_LENGTH = 4;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.floreantpos.swing.PosButton btnCancel;
    private com.floreantpos.swing.PosButton btnOk;
    private javax.swing.JLabel lblPIN;
    private javax.swing.JLabel lblTEI;
    private com.floreantpos.ui.TitlePanel titlePanel1;
    private javax.swing.JFormattedTextField txtPIN;
    private javax.swing.JFormattedTextField txtTEI;
    // End of variables declaration//GEN-END:variables
	
    MaskFormatter teiFormatter = null;
	MaskFormatter pinFormatter = null;
	
	
	/**
	 * Creates new form ScipioDialog
	 */
	public ScipioDialog() {
		super(Application.getPosWindow(), true, false);
		System.out.println("in ScipioDialog constructor");
		
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
	
        try {
			teiFormatter = new MaskFormatter("#####");
			pinFormatter = new MaskFormatter("####");
		} catch (ParseException e) {
			e.printStackTrace();
		}
        
		initComponents();
		
//		txtTEI.setDocument(new LimitedNumericInput(TEI_MAX_LENGTH));
//		txtPIN.setDocument(new LimitedNumericInput(PIN_MAX_LENGTH));
		setResizable(false);
        pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        titlePanel1 = new com.floreantpos.ui.TitlePanel();
        lblTEI = new javax.swing.JLabel();
        btnOk = new com.floreantpos.swing.PosButton();
        btnCancel = new com.floreantpos.swing.PosButton();
        txtTEI = new javax.swing.JFormattedTextField(teiFormatter);
        lblPIN = new javax.swing.JLabel();
        txtPIN = new javax.swing.JFormattedTextField(pinFormatter);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCIPIO INFORMATION");

        titlePanel1.setTitle("SCIPIO INFORMATION");

        lblTEI.setText("TEI:");
        lblTEI.setMaximumSize(new java.awt.Dimension(32, 16));
        lblTEI.setMinimumSize(new java.awt.Dimension(16, 16));
        lblTEI.setPreferredSize(new java.awt.Dimension(32, 16));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finish_32.png"))); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doOk(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_32.png"))); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doCancel(evt);
            }
        });

        txtTEI.setText("12345");
        txtTEI.setMaximumSize(new java.awt.Dimension(250, 30));
        txtTEI.setMinimumSize(new java.awt.Dimension(24, 20));

        lblPIN.setText("PIN:");
        lblPIN.setMaximumSize(new java.awt.Dimension(32, 16));
        lblPIN.setMinimumSize(new java.awt.Dimension(16, 16));
        lblPIN.setPreferredSize(new java.awt.Dimension(32, 16));

        txtPIN.setText("1234");
        txtPIN.setMaximumSize(new java.awt.Dimension(250, 30));
        txtPIN.setMinimumSize(new java.awt.Dimension(24, 20));
        txtPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPIN, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTEI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTEI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtTEI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	public void initData() {
		System.out.println("...in ScipioDialog.initData()");
	}
	
	private void doOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkdoOk
		try {
			System.out.println("...in ScipioDialog.doOk()");
		
			setCanceled(false);
			dispose();
			//TODO: attach TIE & PIN to ticket
		} catch (PosException e) {
			POSMessageDialog.showError(this, e.getMessage());
		}
	}//GEN-LAST:event_btnOkdoOk

	private void doCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanceldoCancel
		System.out.println("... inScipioDialog.doCancel()");
		dispose();
	}//GEN-LAST:event_btnCanceldoCancel

	private void txtPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPINActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtPINActionPerformed


	public Ticket getTicket() {
		return ticket;
	}

	public void setTicket(Ticket ticket) {
		this.ticket = ticket;
	}
}
