-- BEGIN TABLE SCIPIO_INFO
CREATE TABLE SCIPIO_INFO 
(
  ID               INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1,INCREMENT BY 1),
  PEI              VARCHAR(6),
  TEI              VARCHAR(5),
  PIN              VARCHAR(4),
  TICKET_ID        INTEGER
);

ALTER TABLE SCIPIO_INFO ADD CONSTRAINT PK_SCIPIO_INFO_ID PRIMARY KEY (ID);

CREATE INDEX APP.SCIPIO_INFO_INDEX_PIN
       ON SCIPIO_INFO (PIN ASC);

CREATE INDEX APP.SCIPIO_INFO_INDEX_TEI
       ON SCIPIO_INFO (TEI ASC);

CREATE INDEX APP.SCIPIO_INFO_INDEX_PEI
       ON SCIPIO_INFO (PEI ASC);

CREATE UNIQUE INDEX APP.SCIPIO_INFO_INDEX_ID ON SCIPIO_INFO (ID ASC);

CREATE INDEX APP.SCIPIO_INFO_INDEX_TICKET_ID
       ON SCIPIO_INFO (TICKET_ID ASC);
-- END TABLE SCIPIO_INFO

 -- BEGIN FOREIGN KEYS
ALTER TABLE SCIPIO_INFO ADD CONSTRAINT FK_SCIPIO_INFO_TICKET_ID FOREIGN KEY (TICKET_ID) 
	REFERENCES TICKET (ID) 
		ON UPDATE NO ACTION 
		ON DELETE NO ACTION;
 -- END FOREIGN KEYS


-- BEGIN ALTER TABLE TICKET --
ALTER TABLE TICKET ADD SCIPIO_INFO_ID INTEGER;

ALTER TABLE TICKET
	ADD CONSTRAINT FK_TICKET_SCIPIO_INFO_ID FOREIGN KEY (SCIPIO_INFO_ID)
	REFERENCES SCIPIO_INFO (ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION;
   
-- END ALTER TABLE TICKET --


-- BEGIN ALTER TABLE RESTAURANT --
ALTER TABLE RESTAURANT ADD SMI INTEGER;
-- END ALTER TABLE RESTAURANT --

COMMIT

