//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.21 at 09:16:53 AM COT 
//


package scipio.xml.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the scipio.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: scipio.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Receipt }
     * 
     */
    public Receipt createReceipt() {
        return new Receipt();
    }

    /**
     * Create an instance of {@link Receipt.Payment }
     * 
     */
    public Receipt.Payment createReceiptPayment() {
        return new Receipt.Payment();
    }

    /**
     * Create an instance of {@link Receipt.Payment.Card }
     * 
     */
    public Receipt.Payment.Card createReceiptPaymentCard() {
        return new Receipt.Payment.Card();
    }

    /**
     * Create an instance of {@link Receipt.Transaction }
     * 
     */
    public Receipt.Transaction createReceiptTransaction() {
        return new Receipt.Transaction();
    }

    /**
     * Create an instance of {@link Receipt.Transaction.Discounts }
     * 
     */
    public Receipt.Transaction.Discounts createReceiptTransactionDiscounts() {
        return new Receipt.Transaction.Discounts();
    }

    /**
     * Create an instance of {@link Receipt.Transaction.Discounts.Coupons }
     * 
     */
    public Receipt.Transaction.Discounts.Coupons createReceiptTransactionDiscountsCoupons() {
        return new Receipt.Transaction.Discounts.Coupons();
    }

    /**
     * Create an instance of {@link Receipt.Transaction.Items }
     * 
     */
    public Receipt.Transaction.Items createReceiptTransactionItems() {
        return new Receipt.Transaction.Items();
    }

    /**
     * Create an instance of {@link Receipt.Transaction.Items.Item }
     * 
     */
    public Receipt.Transaction.Items.Item createReceiptTransactionItemsItem() {
        return new Receipt.Transaction.Items.Item();
    }

    /**
     * Create an instance of {@link Receipt.Merchant }
     * 
     */
    public Receipt.Merchant createReceiptMerchant() {
        return new Receipt.Merchant();
    }

    /**
     * Create an instance of {@link Receipt.Application }
     * 
     */
    public Receipt.Application createReceiptApplication() {
        return new Receipt.Application();
    }

    /**
     * Create an instance of {@link Receipt.Pos }
     * 
     */
    public Receipt.Pos createReceiptPos() {
        return new Receipt.Pos();
    }

    /**
     * Create an instance of {@link Receipt.Terminal }
     * 
     */
    public Receipt.Terminal createReceiptTerminal() {
        return new Receipt.Terminal();
    }

    /**
     * Create an instance of {@link Receipt.Consumer }
     * 
     */
    public Receipt.Consumer createReceiptConsumer() {
        return new Receipt.Consumer();
    }

    /**
     * Create an instance of {@link Receipt.Payment.Card.CardHolder }
     * 
     */
    public Receipt.Payment.Card.CardHolder createReceiptPaymentCardCardHolder() {
        return new Receipt.Payment.Card.CardHolder();
    }

    /**
     * Create an instance of {@link Receipt.Transaction.Salestax }
     * 
     */
    public Receipt.Transaction.Salestax createReceiptTransactionSalestax() {
        return new Receipt.Transaction.Salestax();
    }

    /**
     * Create an instance of {@link Receipt.Transaction.Discounts.Coupons.Coupon }
     * 
     */
    public Receipt.Transaction.Discounts.Coupons.Coupon createReceiptTransactionDiscountsCouponsCoupon() {
        return new Receipt.Transaction.Discounts.Coupons.Coupon();
    }

    /**
     * Create an instance of {@link Receipt.Transaction.Items.Item.Coupon }
     * 
     */
    public Receipt.Transaction.Items.Item.Coupon createReceiptTransactionItemsItemCoupon() {
        return new Receipt.Transaction.Items.Item.Coupon();
    }

    /**
     * Create an instance of {@link Receipt.Merchant.Address }
     * 
     */
    public Receipt.Merchant.Address createReceiptMerchantAddress() {
        return new Receipt.Merchant.Address();
    }

}
